package com.tjeoun.newssearch.enums;

public enum AdminLogEnum {
    CREATE_ARTICLE, MODIFY_ARTICLE, DELETE_ARTICLE, MODIFY_NEWS, DELETE_NEWS, SUSPEND_MEMBER, MODIFY_MEMBER, DELETE_NEWS_REPLY, DELETE_BOARD_REPLY
}
